# SPDX-License-Identifier: GPL-2.0

ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(DEVICE_MODULES_PATH)/drivers/gpu/drm/mediatek/mediatek_v2/
ccflags-y += -I$(srctree)/drivers/leds

obj-$(CONFIG_LEDS_TRIGGER_BACKLIGHT_DRM) += ledtrig-backlight-drm.o
